### ISSUE TITLE
Escritura del código de identificación animal en fichero de texto

### ISSUE THREAD

**Issue by RebekkaVision** [celiagarcia/AIVA_2023-Crotales#10]
Escritura del código de identificación animal en fichero de texto: el código de cuatro dígitos obtenido en el paso anterior se almacena en un fichero de texto.
Origen: el código extraído en el paso anterior se almacena en el fichero de texto CrotalCode.txt que debe existir o crearse en caso contrario.
Desarrollo y test: se precisan las 100 imágenes anteriores.

**Comment by RVillarraso** [comment]
Created the class ExportCode in ExportCode.py file attached in ExportCode.zip file
Uploaded file 
[ExportCode.zip](https://github.com/celiagarcia/AIVA_2023-Crotales/files/11242817/ExportCode.zip)

**Comment by RebekkaVision** [comment]
Updated ExportCode.py
