### ISSUE TITLE
Definir test

### ISSUE THREAD

**Issue by celiagarcia** [celiagarcia/AIVA_2023-Crotales#18]
Definir los diferentes test unitarios que se van a llevar a cabo durante el desarrollo de la aplicación y que nos aseguren su correcto funcionamiento, y que se ajusten a los requisitos de sistema ya definidos.

1.  Tests unitarios para el bloque "**Lectura de imagen**":
- [x] test positivo con ruta de la imagen correcta y carga de imagen correcta.
- [x] test negativo con ruta de imagen incorrecta o vacía.
- [x] test negativo con ruta de imagen correcta pero formato de imagen incorrecta.
2. Tests unitarios para el bloque "**Procesar imagen**":
- [x] test positivo para verificar que la imagen está en formato correcto (binaria: nº de canales correcto).
- [x] test negativo para verificar que se detecta que la imagen no está en formato correcto (nº de canales incorrecto).
3. Tests unitarios para el bloque "**Leer códigos**":
- [x] test positivo se verifica que el código leído es correcto (contra Ground Truth).
- [x] test negativo se verifica que el código retornado no es correcto (contra Ground Truth). 
4. Tests unitarios para el bloque "**Escritura de código**":
- [x] test positivo, se verifica que se escribe en fichero el código leído.
- [x] test negativo, se verifica que se escribe en el fichero de salida algún mensaje de imposibilidad de lectura de código u error.
5. Tests de integración para el bloque "**Integración**":
- [x] se verifica test positivos y negativos en entorn de producción.

**Comment by RVillarraso** [comment]
Se han implementado dos grupos de test, un grupo de test positivo que consta de un test que verifica varias funcionalidades y un test negativo que consta de cinco tests. Dichos tests están implementados en Testing_CrotalCodeExtractor.py y su ejecución está automatizada. Únicamente se debe ejecutar el fichero Testing_CrotalCodeExtractor.exe.

**Comment by RebekkaVision** [comment]
Para ejecutar el test automatizado ejecutar el fichero Testing_CrotalCodeExtractor.exe o Testing_CrotalCodeExtractor.py:
https://urjc-my.sharepoint.com/:u:/r/personal/r_villarraso_2021_alumnos_urjc_es/Documents/PRACTICA_CROTALES/PRACTICA2/[Testing_CrotalCodeExtractor.exe](https://urjc-my.sharepoint.com/:u:/r/personal/r_villarraso_2021_alumnos_urjc_es/Documents/PRACTICA_CROTALES/PRACTICA2/Testing_CrotalCodeExtractor.exe?csf=1&web=1&e=EazU7U)?csf=1&web=1&e=EazU7U
