### ISSUE TITLE
Implementar lectura de imagenes

### ISSUE THREAD

**Issue by RebekkaVision** [celiagarcia/AIVA_2023-Crotales#6]
Lectura de imágenes: lectura de imagen en escala de grises a partir de una ruta dada.
Origen: la aplicación Visual Basic envía al programa CrotalReading la ruta de la imagen a leer en formato .tif y en escala de grises.
Desarrollo y test: se precisan 100 imágenes reales en formato .tif en escala de grises y con códigos de identificación animal con diferentes inclinaciones.

**Comment by RebekkaVision** [comment]
Added CrotalReading.py code on Github project.
Implemented load gray image functionality

**Comment by RebekkaVision** [comment]
Pendiente, implementar la gestión de errores de imágenes con formato incorrecto, o ruta de imagen incorrecta (imagen no existe, ruta vacía, imagen no se encuentra, etc).

**Comment by RVillarraso** [comment]
Implemented class ReadImage in ReadImage.py attached in ReadImage.zip file.
[ReadImage.zip](https://github.com/celiagarcia/AIVA_2023-Crotales/files/11239266/ReadImage.zip)
