### ISSUE TITLE
Preprocesado de imagen

### ISSUE THREAD

**Issue by RebekkaVision** [celiagarcia/AIVA_2023-Crotales#7]
Binarizar imagen: la imagen leída se transforma a binaria.
Origen: para facilitar la localización e identificación de dígitos se binariza la imagen.
Desarrollo y test: se precisan las 100 imágenes anteriores.

**Comment by RVillarraso** [comment]
Created ProcessImage class in ProcessImage.py file attached in ProcessImage.zip 
Uploaded file
[Uploading ProcessImage.zip…]()
