### ISSUE TITLE
Localizar código de identificación animal

### ISSUE THREAD

**Issue by RebekkaVision** [celiagarcia/AIVA_2023-Crotales#8]
Localizar código de identificación animal: localización de los cuatro dígitos que forman el código de identificación animal de la imagen del crotal. 
Origen: los dígitos están situados en la parte inferior del crotal con el tamaño de dígito mayor al resto de información del crotal. El crotal puede estar inclinado un número indeterminado de grados, por lo que los códigos a localizar, también pueden estarlo.
Desarrollo y test: se precisan las 100 imágenes anteriores.

**Comment by RVillarraso** [comment]
Not implemented code localization, extracted code directly
