### ISSUE TITLE
Leer código de identificación animal

### ISSUE THREAD

**Issue by RebekkaVision** [celiagarcia/AIVA_2023-Crotales#9]
Leer código de identificación animal: leer las cuatro cifras del código de identificación animal de los cuatro dígitos localizados en la imagen del crotal.
Origen: los dígitos localizados pueden estar en formato de texto tipo arial o semejante.
Desarrollo y test: se precisan las 100 imágenes anteriores y un documento que contenga los códigos de identificación animal reales (ground truth).

**Comment by RVillarraso** [comment]
Extract identification code in class ProcessImageattached in ProcessImage.zip file
[ProcessImage.zip](https://github.com/celiagarcia/AIVA_2023-Crotales/files/11242756/ProcessImage.zip)

Updated ProcessImage file
